### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by ice1000** [covscript/covscript-imgui#2]
Copied covscript's `include` dir.

Run `make.sh` get

```
~/git-repos/LanguageCompilers/CovScript/covscript-imgui λ> ./make.sh
/usr/bin/ld: //usr/local/lib/libcovscript.a(extension.cpp.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
//usr/local/lib/libcovscript.a: 无法添加符号: 错误的值
collect2: error: ld returned 1 exit status
/usr/bin/ld: /usr/local/lib/libcovscript.a(extension.cpp.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libcovscript.a: 无法添加符号: 错误的值
collect2: error: ld returned 1 exit status
/usr/bin/ld: /usr/local/lib/libcovscript.a(extension.cpp.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libcovscript.a: 无法添加符号: 错误的值
collect2: error: ld returned 1 exit status
```

**Comment by mikecovlee** [comment]
https://github.com/covscript/covscript/commit/74f04460185e6f0520e319981d2991c8acfd627a

**Comment by imkiva** [comment]
Same as macOS

**Comment by mikecovlee** [comment]
I added the `-fPIC` option to CMake script, it should works now. Can you test it again? It works well when I uses CSBuild to build the `libcovscript.a`.

**Comment by ice1000** [comment]
How the fuck can I install covscript's .a apart from copying and pasting it into `/usr/local/lib`?

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/49975325-6dffbd80-ff0b-11e8-9623-155f1ce46b0b.png)

I didn't see any problem running the examples.

**Comment by ice1000** [comment]
Why the fuck doesn't covscript's cli tool support a `--help` flag?

```
~/git-repos/LanguageCompilers/CovScript/covscript-imgui λ> cs --help
Fatal Error: argument syntax error.
~/git-repos/LanguageCompilers/CovScript/covscript-imgui λ> cs --version
Fatal Error: argument syntax error.
~/git-repos/LanguageCompilers/CovScript/covscript-imgui λ> cs -version
Fatal Error: argument syntax error.
~/git-repos/LanguageCompilers/CovScript/covscript-imgui λ> cs -help
Fatal Error: argument syntax error.
~/git-repos/LanguageCompilers/CovScript/covscript-imgui λ> cs help
Fatal Error: help: No such file or directory
```

**Comment by mikecovlee** [comment]
https://github.com/covscript/covscript/blob/master/README.md

**Comment by mikecovlee** [comment]
The problems are in the `tests/test.csc`.

**Comment by ice1000** [comment]
```
~/git-repos/LanguageCompilers/CovScript/covscript-imgui λ> cs tests/test.csc
Uncaught exception: Unknown exception
```

Great. How am I supposed to debug this?

**Comment by ice1000** [comment]
Reinstalled covscript. Now I can't run any files under the `tests` folder. All of them gives me the same error as above.

**Comment by mikecovlee** [comment]
GLFW static object error, see `imgui_gl3.cpp`.

**Comment by ice1000** [comment]
How am I supposed to debug that?
Didn't find any related codes in the file you specified

**Comment by mikecovlee** [comment]
Main code located in `imgui.cpp`, you can see a static GLFW initiator.

**Comment by ice1000** [comment]
I don't think it's related to GLFW. Before reinstalling, everything works fine.

**Comment by mikecovlee** [comment]
Have you tested other extension? Do they works well?

**Comment by mikecovlee** [comment]
If not, that is a truly big problem. Maybe the extension system causes these uncaught exception.

**Comment by mikecovlee** [comment]
But the truth is that each tests of all extensions have been succeeded in Microsoft Windows Platform using CSBuild.

**Comment by imkiva** [comment]
> But the truth is that each tests of all extensions have been succeeded in Microsoft Windows Platform using CSBuild.

Windows IS FULL OF SHIT. 
SOMETHING THAT RUNS SUCCESSFULLY CANNOT RUN AS EXPECTED ON Linux

**Comment by imkiva** [comment]
Should be closed

**Comment by ice1000** [comment]
>           Should be closed

Why?
